version: "3.8"

services:
  backend:
    build: .
    container_name: backend
    ports:
      - "5000:5000" 
    depends_on:
      - postgres  
    environment:
      DATABASE_URL: postgresql://admin:admin@postgres_db:5432/render?sslmode=disable
      PORT: 5000

  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: render
    ports:
      - "5433:5432" 
    volumes:
      - pgdata:/var/lib/postgresql/data  

volumes:
  pgdata:
