version: "3.8"

services:
  backend:
    build: .
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://admin:hElMyhLhoQeZayQPCHAe7if0Uc1kOJwV@dpg-cvel4vpc1ekc73eg9r7g-a.oregon-postgres.render.com/render_734j
      PORT: 5000

volumes:
  pgdata:
